// restless without u... without u...
// u cut out a peace of me....
// n now i bleed internally... 
// left here without u... without u....

// and it hurts for me to think about wha life could possibly be like...
// without u... without yaaa.....

// i cant believe it... u bout to leave me... 
// fuck all o ur reasons... i too lost our shit.. 
// u know i didnt mean it... now i see it...
// U RUN AND REPEAT IT...
// and i cant take it back so in the PAST is wha i believe ayy

// huh

// so there i go oh...
// cant make a wife outta u woah.. oh..
// i've never find the words to say im sorry but im scared to be aloneee......

// u cut out a peace of me....
// n now i bleed internally... 
// left here without u... without u....

// and it hurts for me to think about wha life could possibly be like...
// without u... without yaaa.....





// dk how, it got tragic
// Cause inside, we wreak havoc
// Yeah, idk when this
// Yeah, idk when this drastic, where it's goin'
// When I back up emotions
// All they say, I'm controllin'
// When I'm back in tha