
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/client/Appbar";  
import RecoidContextProvider from "./recoilContextProvider";
import { useRecoilValue } from "recoil";
import { whereIsNav } from "@/store/selectors/whereIsNav";
import Bar from "./bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <RecoidContextProvider>
      <body className={inter.className}> 
        {/* <Appbar /> */}
        {/* {isUser ? <Appbar /> : <AdminAppbar />}  */}
        {/* {!isUser && <AdminAppbar />} */}
        {<Bar />}
        {children}
      </body> 
      </RecoidContextProvider>
    </html>
  );
}
