
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/client/Appbar";  
import RecoidContextProvider from "./recoilContextProvider";
import { useRecoilValue } from "recoil";
import { whereIsNav } from "@/store/selectors/whereIsNav";
import Bar from "./bar";
import { AuthContextProvider } from "./AuthContext" 
import { Toaster } from "react-hot-toast"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>  
      <RecoidContextProvider>
        <AuthContextProvider>
        <Toaster />
        {/* <Appbar /> */}
        {/* {isUser ? <Appbar /> : <AdminAppbar />}  */}
        {/* {!isUser && <AdminAppbar />} */}
        {<Bar />}
        {children}
        </AuthContextProvider>
      </RecoidContextProvider>
      </body> 
      
    </html>
  );
}
